In [1]:
import pandas as pd # importing pandas as pd
import numpy  as np # importing numpy as np

In [40]:
nums = [1, 2, 3, 4,5]
s = pd.Series(nums)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [41]:
nums = [1, 2, 3, 4, 5]
s = pd.Series(nums, index=[1, 2, 3, 4, 5])
print(s)

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [42]:
fruits = ['Orange','Banana','Mango']
fruits = pd.Series(fruits, index=[1, 2, 3])
print(fruits)

1    Orange
2    Banana
3     Mango
dtype: object

In [43]:
#Creating Pandas Series from a Dictionary
dct = {'name':'sandeep','country':'canada','city':'toronto'}
s = pd.Series(dct)
print(s)

name       sandeep
country     canada
city       toronto
dtype: object

In [44]:
#Creating DataFrames from List of Lists
data = [
    ['sandeep', 'Canada', 'Toronto'],
    ['David', 'UK', 'London'],
    ['John', 'Sweden', 'Stockholm']
]
df = pd.DataFrame(data, columns=['Names','Country','City'])
print(df)

     Names Country       City
0  sandeep  Canada    Toronto
1    David      UK     London
2     John  Sweden  Stockholm

In [7]:
#Creating DataFrame Using Dictionary
data = {'Name': ['sandeep', 'David', 'John'], 'Country':[
    'Canada', 'UK', 'Sweden'], 'City': ['Helsiki', 'London', 'Stockholm']}
df = pd.DataFrame(data)
print(df)

      Name Country       City
0  sandeep  Canada    Helsiki
1    David      UK     London
2     John  Sweden  Stockholm

In [45]:
#Creating DataFrames from a List of Dictionaries
data = [
    {'Name': 'sandeep', 'Country': 'Canada', 'City': 'Toronto'},
    {'Name': 'David', 'Country': 'UK', 'City': 'London'},
    {'Name': 'John', 'Country': 'Sweden', 'City': 'Stockholm'}]
df = pd.DataFrame(data)
print(df)

      Name Country       City
0  sandeep  Canada    Toronto
1    David      UK     London
2     John  Sweden  Stockholm

In [46]:
import pandas as pd

df = pd.read_csv('weight-height.csv')
print(df)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [10]:
print(df.head()) # give five rows we can increase the number of rows by passing argument to the head() method

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [11]:
print(df.tail()) # tails give the last five rows, we can increase the rows by passing argument to tail method

      Gender     Height      Weight
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

In [12]:
print(df.shape) # as you can see 10000 rows and three columns

(10000, 3)

In [13]:
print(df.columns)

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [50]:
heights = df['Height'] # this is now a series
print(heights)
#print(df['Height'])

0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...
9995    66.172652
9996    67.067155
9997    63.867992
9998    69.034243
9999    61.944246
Name: Height, Length: 10000, dtype: float64

In [51]:
weights = df['Weight'] # this is now a series
print(weights)

0       241.893563
1       162.310473
2       212.740856
3       220.042470
4       206.349801
           ...
9995    136.777454
9996    170.867906
9997    128.475319
9998    163.852461
9999    113.649103
Name: Weight, Length: 10000, dtype: float64

In [52]:
print(len(heights) == len(weights))

True

In [17]:
print(heights.describe()) # give statistical information about height data
print(weights.describe())

count    10000.000000
mean        66.367560
std          3.847528
min         54.263133
25%         63.505620
50%         66.318070
75%         69.174262
max         78.998742
Name: Height, dtype: float64
count    10000.000000
mean       161.440357
std         32.108439
min         64.700127
25%        135.818051
50%        161.212928
75%        187.169525
max        269.989699
Name: Weight, dtype: float64

In [18]:
print(df.describe())  # describe can also give statistical information from a dataFrame

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

Modifying a DataFrame
Creating a DataFrame

In [53]:
import pandas as pd
import numpy as np
data = [
    {"Name": "Sandeep", "Country":"Canada","City":"Toronto"},
    {"Name": "David", "Country":"UK","City":"London"},
    {"Name": "John", "Country":"Sweden","City":"Stockholm"}]
df = pd.DataFrame(data)
print(df)

      Name Country       City
0  Sandeep  Canada    Toronto
1    David      UK     London
2     John  Sweden  Stockholm

In [54]:
weights = [74, 78, 69]
df['Weight'] = weights
df

      Name Country       City  Weight
0  Sandeep  Canada    Toronto      74
1    David      UK     London      78
2     John  Sweden  Stockholm      69

In [21]:
heights = [173, 175, 169]
df['Height'] = heights
print(df)

      Name Country       City  Weight  Height
0  Sandeep  Canada    Toronto      74     173
1    David      UK     London      78     175
2     John  Sweden  Stockholm      69     169

In [22]:
df['Height'] = df['Height'] * 0.01
df

      Name Country       City  Weight  Height
0  Sandeep  Canada    Toronto      74    1.73
1    David      UK     London      78    1.75
2     John  Sweden  Stockholm      69    1.69

In [23]:
# Using functions makes our code clean, but you can calculate the bmi without one
def calculate_bmi ():
    weights = df['Weight']
    heights = df['Height']
    bmi = []
    for w,h in zip(weights, heights):
        b = w/(h*h)
        bmi.append(b)
    return bmi

bmi = calculate_bmi()

In [24]:
df['BMI'] = bmi
df

      Name Country       City  Weight  Height        BMI
0  Sandeep  Canada    Toronto      74    1.73  24.725183
1    David      UK     London      78    1.75  25.469388
2     John  Sweden  Stockholm      69    1.69  24.158818

In [25]:
#Formatting DataFrame columns

In [26]:
df['BMI'] = round(df['BMI'], 2)
print(df)

      Name Country       City  Weight  Height    BMI
0  Sandeep  Canada    Toronto      74    1.73  24.73
1    David      UK     London      78    1.75  25.47
2     John  Sweden  Stockholm      69    1.69  24.16

In [57]:
birth_year = ['1769', '1985', '1990']
current_year = pd.Series(2020, index=[0, 1,2])
df['Birth Year'] = birth_year
df['Current Year'] = current_year
df

      Name Country       City  Weight Birth Year  Current Year
0  Sandeep  Canada    Toronto      74       1769          2020
1    David      UK     London      78       1985          2020
2     John  Sweden  Stockholm      69       1990          2020

In [55]:
#Checking data types of Column values
print(df.Weight.dtype)

int64

In [58]:
df['Birth Year'].dtype # it gives string object , we should change this to number

dtype('O')

In [59]:
df['Birth Year'] = df['Birth Year'].astype('int')
print(df['Birth Year'].dtype) # let's check the data type now
df['Current Year'] = df['Current Year'].astype('int')
df['Current Year'].dtype

int64

dtype('int64')

In [31]:
ages = df['Current Year'] - df['Birth Year']
ages

0    251
1     35
2     30
dtype: int64

In [32]:
df['Ages'] = ages
print(df)

      Name Country       City  Weight  Height    BMI  Birth Year  \
0  Sandeep  Canada    Toronto      74    1.73  24.73        1769
1    David      UK     London      78    1.75  25.47        1985
2     John  Sweden  Stockholm      69    1.69  24.16        1990

   Current Year  Ages
0          2020   251
1          2020    35
2          2020    30

In [62]:

df = pd.read_csv('data.csv')
print(df)
new_df = df.dropna()
df.dropna(inplace = True)
#print(df)
print(new_df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0
    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [34]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mean()

df.fillna({"Calories": x}, inplace=True)

In [35]:
df = pd.read_csv('data.csv')

df['Date'] = pd.to_datetime(df['Date'], format='mixed')

print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [36]:
#data correction

In [64]:
df.loc[7, 'Duration'] = 45

In [65]:
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    print(df.loc[x, "Duration"]  )

In [39]:
print(df.duplicated())
df.drop_duplicates(inplace = True)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool